[package]
name = "bufstream2"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
repository = "https://github.com/avl/bufstream2"

[dependencies]


[dev-dependencies]
rand = { version = "0.8", features = ["small_rng"] }
